name: WoolWars
version: ${version}
main: me.cubecrafter.woolwars.WoolWars
api-version: 1.13
description: Fight to take control of the wool at the center of the map!
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - Spigot-Party-API-PAF